# Generated by Django 5.0.2 on 2024-07-27 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.CharField(max_length=50, unique=True)),
                ('jefe_familia', models.CharField(max_length=100)),
                ('nombre_apellidos', models.CharField(max_length=200)),
                ('fecha_nacido', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosCorporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('imc', models.FloatField()),
                ('porcentaje_grasa_corporal', models.FloatField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='NotaSOAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('contrasenha', models.CharField(blank=True, max_length=125)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaCronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_control', models.DateField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaTransitorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fechas', models.JSONField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pulso', models.IntegerField()),
                ('presion_arterial', models.CharField(max_length=20)),
                ('temperatura', models.FloatField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('saturacion_oxigeno', models.FloatField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.historiaclinica')),
            ],
        ),
    ]
