# Generated by Django 5.0.2 on 2024-07-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='documento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_nacido',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='jefe_familia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
