# Generated by Django 5.0.2 on 2024-08-04 01:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_historiaclinica_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='fecha_nacido',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='nombre_apellidos',
        ),
        migrations.RemoveField(
            model_name='problemacronico',
            name='fecha_control',
        ),
        migrations.RemoveField(
            model_name='problematransitorio',
            name='fechas',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='perfil_usuario',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='consultas.perfilusuario'),
        ),
        migrations.AddField(
            model_name='problemacronico',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problematransitorio',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='imc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='perimetro_cefalico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='talla',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='domicilio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='estado_civil',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='jefe_familia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='prontuario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notasoap',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='saturacion_oxigeno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.DeleteModel(
            name='DatosCorporales',
        ),
    ]
