# Generated by Django 5.0.2 on 2024-08-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_remove_historiaclinica_fecha_nacido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='perfil_usuario',
        ),
    ]
