# Generated by Django 5.0.2 on 2024-08-04 03:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_remove_historiaclinica_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='nombre',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
