# Generated by Django 5.0.2 on 2024-08-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_historiaclinica_fecha_historiaclinica_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='perimetro_cefalico',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
